# Buscar todos os Livros
GET http://localhost:8000/api/books/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA2MzA3MTc5LCJpYXQiOjE3MDYzMDY4NzksImp0aSI6ImNlMzY4NzA3YzkyNDRhNmFiZDFjOGQ3MTk1ZWVkMDYxIiwidXNlcl9pZCI6MX0.5dKQ4tCwa16FJ8NoLblR-W2VmpGia8jrfmJtpbxVQsM

###

# Criar um novo livro
POST http://localhost:8000/books/create/
Content-Type: application/json

{
  "title": "Livro Novo",
  "author": 1,
  "created_at": "25-01-2020",
  "published_date": "25-01-2022"
}

###

# Obter detalhes de um livro específico
GET http://localhost:8000/books/1/

###

# Atualizar um livro existente
PUT http://localhost:8000/books/update/1/
Content-Type: application/json

{
  "title": "Livro Atualizado",
  "author": 1,
  "published_date": "2022-01-25"
}

###

# Excluir um livro
DELETE http://localhost:8000/books/delete/1/
